cmd.exe-debug:mycmd.c
	gcc -o $@ $^ -g
.PHONY:clean
clean:
	rm -f cmd.exe

#cmd.exe:mycmd.c
#	gcc -o $@ $^                                                                                                                                                 
#.PHONY:clean
#clean:
#	rm -f cmd.exe
