#myproc:myproc.cc
#	g++ -o $@ $^
#.PHONY:clean
#clean:
#	rm -f myproc

#My_myexec:My_myexec.c
#	gcc -o $@ $^
#.PHONY:clean
#clean:
#	rm -f My_myexec

#myexec:myexec.c
#	gcc -o $@ $^
#.PHONY:clean
#clean:
#	rm -f myexec

#myexec:myexec.c
#	gcc -o $@ $^ -std=c99
#.PHONY:clean
#clean:
#	rm -f myexec

myexec:myexec.c
	gcc -o $@ $^
.PHONY:clean
clean:
	rm -f myexec
